CREATE DATABASE "RxTerms" WITH OWNER "postgres";

CREATE TABLE IF NOT EXISTS "RXTERMS"
(
  "RXCUI"                VARCHAR(8)    NOT NULL,
  "GENERIC_RXCUI"        VARCHAR(8),
  "TTY"                  VARCHAR(20)   NOT NULL,
  "FULL_NAME"            VARCHAR(3000) NOT NULL,
  "RXN_DOSE_FORM"        VARCHAR(100)  NOT NULL,
  "FULL_GENERIC_NAME"    VARCHAR(3000) NOT NULL,
  "BRAND_NAME"           VARCHAR(500),
  "DISPLAY_NAME"         VARCHAR(3000) NOT NULL,
  "ROUTE"                VARCHAR(100)  NOT NULL,
  "NEW_DOSE_FORM"        VARCHAR(100)  NOT NULL,
  "STRENGTH"             VARCHAR(500)  NOT NULL,
  "SUPPRESS_FOR"         VARCHAR(30),
  "DISPLAY_NAME_SYNONYM" VARCHAR(500),
  "IS_RETIRED"           VARCHAR(8),
  "SXDG_RXCUI"           VARCHAR(8),
  "SXDG_TTY"             VARCHAR(20),
  "SXDG_NAME"            VARCHAR(3000),
  "PSN"                  VARCHAR(3000),
  CONSTRAINT "RXTERMS_pk" PRIMARY KEY ("RXCUI")
);

CREATE UNIQUE INDEX IF NOT EXISTS "RXTERMS_RXCUI_uindex" ON "RXTERMS" ("RXCUI");

ALTER TABLE "RXTERMS" OWNER TO "postgres";
